name: End-to-end tests
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Select browser
        default: chrome
        options:
          - electron
          - chrome
          - firefox
          - edge

  push:
    branches: [main]

  pull_request:

env:
  BROWSER: ${{ github.event.inputs.browser || 'chrome' }}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{env.BROWSER || 'chrome'}}
          install-command: npm install
          build: npm run build
          start: npm start
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate report
        if: always()
        continue-on-error: true
        run: npm run test:report

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-cucumber-report
          path: cypress/reports/cucumber-report/

      - name: Deploy report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/cucumber-report

      - name: Push results to jira
        if: always()
        run: |
          curl -X POST https://c4j.cucumber.io/ci/rest/api/results \
          -H "authorization: Bearer ${{ secrets.C4J_TOKEN }}" \
          -H 'content-type: multipart/form-data' \
          -F results_file=@./cypress/reports/cucumber-json/cucumber-report.json \
          -F language=js

      - name: Write summary
        if: always()
        run: |
          echo "[View run in Cucumber Report] (https://leonardust.github.io/todomvc-cypress/)" >> $GITHUB_STEP_SUMMARY
