name: End-to-end tests
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Select browser
        default: chrome
        options:
          - electron
          - chrome
          - firefox
          - edge

  push:
    branches: [main]

  pull_request:

env:
  BROWSER: ${{ github.event.inputs.browser || 'chrome' }}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate auxiliary JSON for authenticating with Xray cloud and obtain token
        run: |
          cat cloud_auth.json.sample \ 
          | sed s/CLIENT_ID/${{ secrets.XRAYCLOUD_CLIENT_ID }}/g \
          | sed s/CLIENT_SECRET/${{ secrets.XRAYCLOUD_CLIENT_SECRET }}/g > cloud_auth.json
          echo token=$(curl -H "Content-Type: application/json" -X POST --data @"cloud_auth.json" ${{ secrets.XRAYCLOUD_BASE_URL }}/api/v1/authenticate| tr -d '"') >> $GITHUB_ENV

      # - name: Export scenarios from Xray and generate .feature file(s)
      #   run: |
      #     FEATURES_FILE=features.zip
      #     rm -f $FEATURES_FILE
      #     curl -H "Content-Type: application/json" -X GET -H "Authorization: Bearer ${{ env.token }}" "${{ secrets.XRAYCLOUD_BASE_URL }}/api/v1/export/cucumber?keys=${{ secrets.XRAYCLOUD_ISSUE_KEYS_TO_EXPORT_FROM }}" -o $FEATURES_FILE
      #     rm -f features/*.feature
      #     unzip -o $FEATURES_FILE  -d e2e

      # - name: Import cucumber scenarios to Xray
      #   run: |
      #     zip -r features.zip cypress/e2e/ -i \*.feature
      #     curl -H "Content-Type: multipart/form-data" -X POST -H -u ${{ secrets.JIRA_USER }}:${{ secrets.JIRA_PASSWORD }}  -F "file=@features.zip" ${{ secrets.JIRA_BASE_URL }}/rest/raven/1.0/import/feature?projectKey=TCC

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{env.BROWSER || 'chrome'}}
          install-command: npm install
          build: npm run build
          start: npm start
          record: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate report
        if: always()
        continue-on-error: true
        run: npm run test:report

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-cucumber-report
          path: cypress/reports/cucumber-report/

      - name: Deploy report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/cucumber-report

      # - name: Push results to Cucumber for Jira
      #   if: always()
      #   run: |
      #     curl -X POST https://c4j.cucumber.io/ci/rest/api/results \
      #     -H "authorization: Bearer ${{ secrets.C4J_TOKEN }}" \
      #     -H 'content-type: multipart/form-data' \
      #     -F results_file=@./cypress/reports/cucumber-json/cucumber-report.json \
      #     -F language=js

      - name: Generate auxiliary JSON to define some fields on the Test Execution to be created
        if: always()
        run: |
          cat testexec_cloud_template.json  | \
          sed s/PROJECT_KEY/${{ secrets.JIRACLOUD_PROJECT_KEY }}/g | \
          sed s/TESTPLAN_KEY/${{ secrets.XRAYCLOUD_TEST_PLAN_KEY }}/g | \
          sed s/TEST_ENVIRONMENT_NAME/${{ env.BROWSER }}/g | \
          sed "s/BEGIN_DATE/$(date -u +'%Y-%m-%dT%H:%M:%S.%3NZ')/g" | \
          sed "s/END_DATE/$(date -u +'%Y-%m-%dT%H:%M:%S.%3NZ')/g" > test_exec.json

      - name: Debug test_exec.json
        if: always()
        run: |
          cat test_exec.json

      - name: Import Test Execution to Xray
        if: always()
        run: |
          curl -X POST -H "Authorization: Bearer ${{ env.token }}"  \
          -F info=@test_exec.json \
          -F results=@"./cypress/reports/cucumber-json/cucumber-report.json" \
          "${{ secrets.XRAYCLOUD_BASE_URL }}/api/v1/import/execution/cucumber/multipart"

      # - name: "Import results to Xray using GH action"
      #   uses: mikepenz/xray-action@v2.3.0
      #   with:
      #     username: ${{ secrets.XRAYCLOUD_CLIENT_ID }}
      #     password: ${{ secrets.XRAYCLOUD_CLIENT_SECRET }}
      #     xrayCloud: "true"
      #     testFormat: "cucumber"
      #     testPaths: "./cypress/reports/cucumber-json/cucumber-report.json"
      #     testExecutionJson: "test_exec.json"

      - name: Write summary
        if: always()
        run: |
          echo "[View run in Cucumber Report](https://leonardust.github.io/todomvc-cypress-cucumber/)" >> $GITHUB_STEP_SUMMARY
