name: End-to-end tests
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Select browser
        default: electron
        options:
          - electron
          - chrome
          - firefox
          - edge

  push:
    branches: [main]

env:
  BROWSER: ${{ github.event.inputs.browser || 'electron' }}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress info
        run: npx cypress info
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{github.event.inputs.browser || 'electron'}}
          install-command: npm install
          build: npm run build
          start: npm start
      - name: Generate report
        run: npm run cy:report
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-cucumber-report
          path: cypress/reports/cucumber-report/
      - name: Deploy report to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/cucumber-report
      - name: Write summary
        if: always()
        run: |
          echo "- Browser: $BROWSER" >> $GITHUB_STEP_SUMMARY
