name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Log Node version
        run: node -v
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          install-command: npm install
          build: npm run build
          start: npm start
